-- AlterTable
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "celular" TEXT;
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "slogan" TEXT;
